version: '3.3'
services:
    zk1:
        image: confluentinc/cp-zookeeper:3.2.2
        deploy:
            replicas: 1
            placement:
                constraints: [engine.labels.availability_zone == us-east-1a]
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
            ZOOKEEPER_SERVERS: 0.0.0.0:2888:3888;zk2:2888:3888;zk3:2888:3888

    zk2:
        image: confluentinc/cp-zookeeper:3.2.2
        deploy:
            replicas: 1
            placement:
                constraints: [engine.labels.availability_zone == us-east-1b]
        environment:
            ZOOKEEPER_SERVER_ID: 2
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
            ZOOKEEPER_SERVERS: zk1:2888:3888;0.0.0.0:2888:3888;zk3:2888:3888

    zk3:
        image: confluentinc/cp-zookeeper:3.2.2
        deploy:
            replicas: 1
            placement:
                constraints: [engine.labels.availability_zone == us-east-1c]
        environment:
            ZOOKEEPER_SERVER_ID: 3
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
            ZOOKEEPER_SERVERS: zk1:2888:3888;zk2:2888:3888;0.0.0.0:2888:3888

    kafka1:
        image: confluentinc/cp-kafka:3.2.2
        deploy:
            replicas: 1
        environment:
            KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk2:2181,zk3:2181"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9092"

    kafka2:
        image: confluentinc/cp-kafka:3.2.2
        deploy:
            replicas: 1
        environment:
            KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk2:2181,zk3:2181"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka2:9092"

    kafka3:
        image: confluentinc/cp-kafka:3.2.2
        deploy:
            replicas: 1
        environment:
            KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk2:2181,zk3:2181"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka3:9092"

networks:
  default:
    external:
      name: zkkafka

