FROM twashing/ibgateway-tws-base:latest
MAINTAINER Timothy Washington

COPY install-base.sh /usr/local/bin/
COPY resources/IBControllerStart-paper.sh /root/
COPY resources/IBControllerStart-real.sh /root/
COPY resources/IBController.ini /root/

RUN chmod ug+x /usr/local/bin/install-base.sh

# ENTRYPOINT [ "/bin/bash" ]
ENTRYPOINT [ "/usr/local/bin/install-base.sh" ]