version: '2'
services:
  tws:
    build:
      context: .
      dockerfile: Dockerfile.tws
    environment:
      TWSUSERID: fdemo
      TWSPASSWORD: demouser
      VNC_PASSWORD: some_pass123
    image: twashing/edgarly-tws:latest
    ports:
      - 4001:4001  # API
      - 5900:5900  # VNC
    tty: true
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: twashing/edgarly-app:latest
    volumes:
      - .:/app
  nrepl:
    image: twashing/edgarly-nrepl-base:latest
    # image: clojure
    depends_on:
      - tws
    working_dir: ${PWD}
    ports:
      - 7888:7888
    volumes:
      - .:${PWD}
    entrypoint: lein with-profile +dev repl :headless :host 0.0.0.0 :port 7888
