version: '2'
services:
  app:
    build: .
    environment:
      TWSUSERID: fdemo
      TWSPASSWORD: demouser
      VNC_PASSWORD: some_pass123
    image: twashing/edgarly:latest
    ports:
      - 4001:4001  # API
      - 5900:5900  # VNC
    tty: true
    restart: always
